[package]
name = "rusty-ship"
version = "0.1.0"
edition = "2021"
authors = ["Axel Olsson <olsson.axel@gmail.com>"]
license = "MIT"
publish = false

[dependencies]
axum = { version = "0.6.10", features = ["ws", "headers"] }
futures = "0.3.26"
tokio = { version = "1.26.0", features = ["full"] }
